### ISSUE TITLE
2024: L3 backbone 構築

### ISSUE THREAD

**Issue by sorah** [ruby-no-kai/rubykaigi-net#90]
- SRX (packet mode) 化
```[tasklist]
### Tasks
- [x] brのSRX化
- [x] AWS NAT GatewayのためのStatic NAT実装
- [x] Resolver NLBのためのStatic NAT実装
- [x] Backup AWS VPC Site-to-Site VPN 実装
- [x] 2001:df0:8500:ca22:16::a / 2001:df0:8500:ca22:16::b の BGPピアが上がってない
- [x] なんかIPv6 Loopbackにpingとおらない
- [x] ECMP
```

**Comment by sorah** [comment]
packet mode だと実現できない機能を別で持たせる必要がある

### Static NAT

2種類4アドレスのStatic NATが必要

- NAT Gateway
- Resolver NLB

### VPC Site-to-Site VPN

IPv4 だけなら IX に任せられるけど IPv6 もあるとどうしようって感じ

**Comment by sorah** [comment]
https://docs.aws.amazon.com/vpn/latest/s2svpn/ipv4-ipv6.html

tgw 必須なのだるすぎ! ということで SPOF を許容して IPv4 だけ従来の手段で組みます…

**Comment by sorah** [comment]
br-01-hnd (2023) → tun-01-hnd (2024) 作業用メモ

## 現状

- Gi0 → Uplink A (NGN-X)
- Gi1 → Uplink B (NGN-N)
- Gi2 → Transit Backup
- Gi3 → Transit Main

## 構成変更後

- tun
  - Gi0 → Uplink A (NGN-X)
  - Gi1 → br ge-0/0/0
  - Gi2 → br ge-0/0/1
  - Gi3 → Uplink B (NGN-N)
- br
  - ge-0/0/0 → tun Gi1
  - ge-0/0/1 → tun Gi2
  - ge-0/0/3 → Uplink A
  - ge-0/0/4 → Uplink B
  - ge-0/0/5 → Transit

**Comment by sorah** [comment]
{br,tun}-01.hnd 設置完了

**Comment by sorah** [comment]
![Image](https://github.com/ruby-no-kai/rubykaigi-net/assets/29440/34de95ad-9cad-484c-987a-251d572034e8)

これまで OSPF 再配布してたから良かったけど全部BGPの世界になった結果どうやってバランシングするんだになるのか

**Comment by sorah** [comment]
![image](https://github.com/ruby-no-kai/rubykaigi-net/assets/29440/b5554a1a-c2c5-45a2-b522-54e6758d58d2)

Static NAT 構築完了。AWSからのinputでFBRをかけてVRFでIXに ip nat static させた。NLBもNAT Gatewayも1つの仕組みで完結

https://scrapbox.io/rknet/2024_Backbone#660b12738209e20000979b3f

**Comment by sorah** [comment]
https://github.com/ruby-no-kai/rubykaigi-net/issues/90#issuecomment-2043077013

結局これは 

```
[edit]
rk@er-01-venue# show|compare
[edit protocols bgp group upstream-public]
+    peer-as 65000;
[edit protocols bgp group upstream-public neighbor 2001:df0:8500:ca22:16::a]
-     peer-as 65001;
[edit protocols bgp group upstream-public neighbor 2001:df0:8500:ca22:24::a]
-     peer-as 65002;
[edit protocols bgp group upstream-public neighbor 2001:df0:8500:ca22:32::a]
-     peer-as 65003;
```

```
[edit protocols bgp group venue-public]
rk@br-01-nrt# show|compare
[edit protocols bgp group venue-public]
+  local-as 65000 no-prepend-global-as;
[edit protocols bgp group venue-public neighbor 2001:df0:8500:ca22:202::b]
+   local-as 65002; /* tkyk backward compat */
```

で 0/0, ::/0 から 6500{1,2,3} のかわりに 65000 を使うように変えた
