### ISSUE TITLE
SNMP監視

### ISSUE THREAD

**Issue by hanazuki** [ruby-no-kai/rubykaigi-net#99]
SNMPで情報とってこれるようにして，監視ルールを書く
```[tasklist]
### Tasks
- [x] SRX/EXのBGP peer state
- [x] nat-4 (IX)のNAPTオーバーフロー
- [ ] tun (IX)のIPsec status
- [x] 各APのクライアント数 (WLC)
```

**Comment by sorah** [comment]
```
rk@cs-01-venue> show configuration snmp
filter-interfaces {
    interfaces {
        "!^[xg]e-[0-9]\/[0-9]+\/[0-9]+(\.[0-9]+)?$";
        "!^ae[0-9]+(\.[0-9]+)?$";
        "!^irb.\d+$";
        "!^lo.*$";
        "!^vcp.*$";
    }
    all-internal-interfaces;
}
stats-cache-lifetime 70;
```

filter-interfaces 入れた

**Comment by hanazuki** [comment]
去年，レーザーの受信レベルをちゃんとみてなかったら妙に弱いやつがいたとか反省をした記憶もある

**Comment by hanazuki** [comment]
IPsec SAが壊れたらlink downになって気づけるはずか
